Ext.onReady(function(){
	quesQueryForm = new Ext.form.FormPanel({
		frame:true,
		method:'post',
		items:[
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						columnWidth:.3,
						layout:'form',
						labelWidth:80,
						labelAlign:'right',
						labelSeparator:'：',
						defaults:{width:150},
						items:[
							{
								xtype:'textfield',
								fieldLabel:'知识点',
								name:'quesTitle'
							}
						]
					},
					{
						xtype:'panel',
						columnWidth:.3,
						layout:'form',
						labelWidth:80,
						labelAlign:'right',
						labelSeparator:'：',
						defaults:{width:100},
						items:[
							{
								xtype:'textfield',
								fieldLabel:'课程',
								name:'quesCour'
							}
						]
					}
				]	
			},
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						columnWidth:.3,
						layout:'form',
						labelWidth:80,
						labelAlign:'right',
						labelSeparator:'：',
						defaults:{width:150},
						items:[
							{
								xtype:'combo',
								fieldLabel:'题型',
								name:'quesCate',
								mode:'local',
								triggerAction:'all',
								editable:false,
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','全部'],['1','填空题'],['2','判断题'],['3','单选题'],['4','多选题'],['5','主观题']]
								}),
								value:'',
								valueField:'id',
								displayField:'text',
								hiddenName:'quesCate'
							}
						]
					},
					{
						xtype:'panel',
						columnWidth:.3,
						layout:'form',
						labelWidth:80,
						labelAlign:'right',
						labelSeparator:'：',
						defaults:{width:100},
						items:[
							{
								xtype:'combo',
								fieldLabel:'难度',
								mode:'local',
								triggerAction:'all',
								editable:false,
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','全部'],['0','简单'],['1','一般'],['2','难'],['3','很难']]
								}),
								value:'',
								valueField:'id',
								displayField:'text',
								name:'quesLevel',
								//id:'quesLevel',
								hiddenName:'quesLevel'
							}
						]
					}
				]	
			}
		],
		buttons:[
			{
				text:'查询',
				handler:function(){
					quesStore.reload({params:{start:0,limit:15}});
				}
			},
			{
				text:'重置',
				handler:function(){
					quesQueryForm.getForm().reset();
				}
			}
		]
	});	
});