Ext.onReady(function(){
	courForm = new Ext.form.FormPanel({
		url:path+'cour!save.action',
		method:'post',
		width:300,
		height:300,
		frame:true,
		labelSeparator:'：',
		items:[
		{
			xtype:'hidden',
			name:'courId',
			fieldLabel:'ID'
		},
		{
			xtype:'textfield',
			name:'courName',
			fieldLabel:'名称',
			allowBlank:false
		},
		{
			xtype:'hidden',
			name:'majors',
			fieldLabel:'courMajor'
		},
		{
			xtype:'panel',
			fieldLabel:'所属专业',
			layout:'hbox',
			items:[
			{
				xtype:'textfield',
				name:'majorNames',
				readOnly:true
			},
			{
				xtype:'button',
				text:'...',
				handler:function(){
					majorWin.show();
				}
			}
			]
		},
		{
			xtype:'numberfield',
			name:'courHour',
			fieldLabel:'课时',
			value:0
		},
		{
			xtype:'combo',
			fieldLabel:'公共课',
			name:'courIspubs',
			labelSeparator:'：',
			mode:'local',
			width:100,
			editable:false,
			triggerAction:'all',
			store:new Ext.data.ArrayStore({
				idIndex:0,
				fields:['id','text'],
				data:[['1','是'],['0','否']]
			}),
			displayField:'text',
			valueField:'id',
			hiddenName:'courIspubs',
			hiddenValue:'0'
		},
		{
			xtype:'combo',
			fieldLabel:'状态',
			name:'courInuse',
			labelSeparator:'：',
			mode:'local',
			width:100,
			editable:false,
			triggerAction:'all',
			store:new Ext.data.ArrayStore({
				idIndex:0,
				fields:['id','text'],
				data:[['1','在用'],['0','停用']]
			}),
			displayField:'text',
			valueField:'id',
			hiddenName:'courInuse',
			hiddenValue:'1'
		},
		{
			xtype:'textarea',
			name:'courDesc',
			fieldLabel:'说明',
			autoWidth:true
		}
		]
	});
	courWin = new Ext.Window({
		modal:true,
		title:'增加',
		width:300,
		height:300,
		autoHeight:true,
		cloable:false,
		renderTo:Ext.getBody(),
		closeAction:'hide',
		items:[courForm],
		buttons:[
		{
			text:'保存',
			handler:function(){
				var boo = courForm.getForm().isValid();
				if(boo){
					courForm.getForm().doAction('submit',{
						waitTitle:'请稍候',
						waitMsg:'正在保存请稍候...',
						success:function(frm,opt){
							if(opt.result.success==true){
								var c = opt.result.cour;
								if(opt.result.save==true){
									var Cour = courGrid.getStore().recordType;
									var cour = new Cour({	//创建课程对像
										courId:c.courId,
										courName:c.courName,
										majors:courForm.getForm().findField('majors').getValue(),
										majorNames:courForm.getForm().findField('majorNames').getValue(),
										courIspubs:c.courIspubs,
										courInuse:c.courInuse,
										courHour:c.courHour,
										courDesc:c.courDesc
									});
									courStore.insert(0,cour);
									courGrid.getSelectionModel().selectFirstRow();	
								}else{
									var rc = courGrid.getSelectionModel().getSelected();
									rc.set('courName',c.courName);//一个值一个值的更新课程对像
									rc.set('majors',courForm.getForm().findField('majors').getValue());
									rc.set('majorNames',courForm.getForm().findField('majorNames').getValue());
									rc.set('courIspubs',c.courIspubs);
									rc.set('courInuse',c.courInuse);
									rc.set('courHour',c.courHour);
									rc.set('courDesc',c.courDesc);
								}
								courWin.hide();
							}else{
								Ext.Msg.alert("提示","保存不成功.");
							}
						},
						failure:function(){
							Ext.Msg.alert("服务","保存不成功.");
						}
					});
				}
			}
		},
		{
			text:'关闭',
			handler:function(){
				courWin.hide();
			}
		}
		]
	});
});