Ext.onReady(function(){
	//查询所有专业
	var queryMajorStore = new Ext.data.JsonStore({
		idProperty:'majorId',
		root:'majors',
		url:path+'cour!queryMajor.action',
		fields:[
		{name:'majorId',mapping:'majorId',type:'string'},
		{name:'majorName',mapping:'majorName',type:'string'}
		]
	});
	queryMajorStore.load();
	
	//查询用的Form
	queryCourForm = new Ext.form.FormPanel({
		url:path+'cour!query.action',
		method:'post',
		region:'north',
		frame:true,
		autoHeight:true,
		items:[
			{
				xtype:'panel',
				width:600,
				layout:'hbox',
				items:[
					{
						xtype:'panel',
						width:200,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						items:[
							{
								xtype:'textfield',
								fieldLabel:'课程名称',
								name:'courName',
								width:100,
								labelSeparator:'：'
							}						
						]
					},
					{
						xtype:'panel',
						width:90,
						layout:'form',
						labelAlign:'right',
						labelWidth:40,
						items:[
							{
								xtype:'numberfield',
								fieldLabel:'课时',
								name:'courHour',
								width:40,
								labelSeparator:'：'
							}
						]
					},
					{
						xtype:'panel',
						width:90,
						layout:'form',
						labelAlign:'right',
						labelWidth:40,
						items:[
							{
								xtype:'numberfield',
								fieldLabel:'到',
								name:'courHour2',
								width:40,
								labelSeparator:''
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				width:600,
				layout:'hbox',
				items:[
					{
						xtype:'panel',
						width:200,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						items:[
							{
								xtype:'combo',
								fieldLabel:'公共课',
								name:'courIspubs',
								labelSeparator:'：',
								mode:'local',
								width:100,
								editable:false,
								triggerAction:'all',
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','全部'],['1','是'],['0','否']]
								}),
								value:'',
								displayField:'text',
								valueField:'id',
								hiddenName:'courIspubs',
								hiddenValue:''
							}						
						]
					},
					{
						xtype:'panel',
						width:150,
						layout:'form',
						labelAlign:'right',
						labelWidth:40,
						items:[
							{
								xtype:'combo',
								fieldLabel:'状态',
								name:'courInuse',
								labelSeparator:'：',
								mode:'local',
								width:100,
								editable:false,
								triggerAction:'all',
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','全部'],['1','在用'],['0','停用']]
								}),
								value:'',
								displayField:'text',
								valueField:'id',
								hiddenName:'courInuse',
								hiddenValue:''
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				width:600,
				layout:'hbox',
				items:[
					{
						xtype:'panel',
						width:200,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						items:[
							{
								xtype:'combo',
								fieldLabel:'所属专业',
								labelSeparator:'：',
								mode:'remote',
								width:100,
								editable:false,
								triggerAction:'all',
								store:queryMajorStore,
								displayField:'majorName',
								valueField:'majorId',
								name:'majors',
								hiddenName:'majors',
								hiddenValue:'majorId'
							}						
						]
					}
				]
			}
		],
		buttons:[
			{
				text:'查询',
				handler:function(){
					var params = queryCourForm.getForm().getFieldValues();
					//alert(params.courName+",,"+params.courHour+",,"+params.majors);
					Ext.apply(params,{
						start:0,
						limit:20
					})
					courStore.reload({params:params});
					//alert("Over..")
				}
			},
			{
				text:'重置',
				handler:function(){
					queryCourForm.getForm().reset();
				}
			}
		]
	});
});