Ext.onReady(function(){
	updateForm = new Ext.form.FormPanel({
		labelSeparator:'：',
		labelAlign:'right',
		frame:true,
		url:path+'teac!agree.action',
		method:'post',
		defaults:{width:260},
		items:[
		{
			xtype:'hidden',
			name:'teacId',
			fieldLabel:'ID'
		},
		{
			xtype:'textfield',
			name:'teacName',
			fieldLabel:'姓名',
			readOnly:true
		},
		{
			xtype:'radiogroup',
			id:'teacSex',
			disabled:true,
			items:[
			{
				boxLabel:'男',
				name:'teacSex',
				inputValue:'1'
			},
			{
				boxLabel:'女',
				name:'teacSex',
				inputValue:'0'
			}
			]
		},
		{
			xtype:'hidden',
			name:'teacDept',
			fieldLabel:'部门ID'
		},
		{
			xtype:'panel',
			fieldLabel:'部门',
			layout:'hbox',
			items:[
			{
				xtype:'textfield',
				name:'deptName',
				width:240,
				readOnly:true
			},
			{
				xtype:'button',
				text:'...',
				handler:function(){
					deptWin.show();
				}
			}
			]
		},
		{
			xtype:'radiogroup',
			fieldLabel:'状态',
			id:'teacState',
			items:[
				{
					name:'teacState',
					boxLabel:'待审批',
					inputValue:'0'
				},
				{
					name:'teacState',
					boxLabel:'正常',
					inputValue:'1'
				},
				{
					name:'teacState',
					boxLabel:'不通过',
					inputValue:'2'
				},
				{
					name:'teacState',
					boxLabel:'禁用',
					inputValue:'3'
				}
			]
		},
		{
			xtype:'textfield',
			name:'teacEmail',
			fieldLabel:'邮箱',
			readOnly:true
		},
		{
			xtype:'textfield',
			name:'teacTel',
			fieldLabel:'电话',
			readOnly:true
		}
		]
	});
	
	updateWin = new Ext.Window({
		title:'修改',
		width:500,
		height:500,
		closable:false,
		autoHeight:true,
		modal:true,
		items:[updateForm],
		buttons:[
		{
			text:'保存',
			handler:function(){
				//alert(updateForm.getForm().getValues()['teacState']);
				//alert(updateForm.getForm().findField("teacDept").getValue());
				//alert(updateForm.getForm().findField("deptName").getValue());
				updateForm.getForm().doAction('submit',{
					waitMsg:'正在保存',
					waitTitle:'MSG',
					success:function(frm,op){
						if(op.result.success==true){
							Ext.Msg.alert("提示","保存成功.",function(){
								var record = teacGrid.getSelectionModel().getSelected();
								record.set("teacState",updateForm.getForm().getValues()['teacState']);
								record.set("teacDept",updateForm.getForm().findField("teacDept").getValue());
								record.set("deptName",updateForm.getForm().findField("deptName").getValue());	
								updateWin.hide();
							});
						}else{
							Ext.Msg.alert("提示","保存<font color=red>不</font>成功.");
						}
					},
					failure:function(frm,op){
						Ext.Msg.alert('MSG','访问服务出错.');
					}
				});
			}
		},
		{
			text:'关闭',
			handler:function(){
				updateWin.hide();
			}
		}
		]
	});
	
	//用于组织框架的帮助
	var selectNode = null;						//临时变量,保存选中节点的对像
	var deptTree = new Ext.tree.TreePanel({
		rootVisible:false,
		height:300,
		autoScroll: true,
		dataUrl:path+'dept!query.action',
		root:{
			nodeType:'async',
			text:'组织框架',
			id:'ROOT'
		},
		listeners:{
			beforeload:function(node){
				deptTree.loader.dataUrl=path+'dept!query.action?deptId='+node.id;
			},
			click:function(node){
				selectNode = node;
			}
		}
	});
	var deptWin = new Ext.Window({
		modal:true,
		title:'选择部门',
		width:240,
		height:300,
		closable:false,
		items:[deptTree],
		buttons:[
		{
			text:'确定',
			handler:function(){
				if(selectNode){					//如果有选中节点则设置值
					updateForm.getForm().findField("teacDept").setValue(selectNode.id);
					updateForm.getForm().findField("deptName").setValue(selectNode.text);
				}
				deptWin.hide();
			}
		},
		{
			text:'关闭',
			handler:function(){
				deptWin.hide();
			}		
		}
		]
	});
	
});