Ext.onReady(function(){
	queryClsForm = new Ext.form.FormPanel({		//查询用的表单
		frame:true,
		labelSeparator:'：',
		items:[
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'班级名称',
								name:'clsName'
							}
						]	
					},
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'班主任',
								name:'clsHead'
							}
						]
					},
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'专业',
								name:'clsMajor'
							}
						]
					},
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'学制',
								name:'edusysName'
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						layout:'column',
						columnWidth:.4,
						items:[
							{
								xtype:'panel',
								columnWidth:.5,
								layout:'form',
								labelAlign:'right',
								labelWidth:80,
								defaults:{width:80},
								labelSeparator:'：',
								items:[
									{
										xtype:'datefield',
										fieldLabel:'开班时间',
										editable:false,
										name:'clsBtime',
										format:'Y-m-d'
									}
								]
							},
							{
								xtype:'panel',
								columnWidth:.5,
								layout:'form',
								labelAlign:'right',
								labelWidth:80,
								defaults:{width:80},
								labelSeparator:'：',
								items:[
									{
										xtype:'datefield',
										fieldLabel:'到',
										editable:false,
										name:'clsBtime2',
										format:'Y-m-d'
									}
								]
							}
						]
					},
					{
						xtype:'panel',
						layout:'column',
						columnWidth:.4,
						items:[
							{
								xtype:'panel',
								columnWidth:.5,
								layout:'form',
								labelAlign:'right',
								labelWidth:80,
								defaults:{width:80},
								labelSeparator:'：',
								items:[
									{
										xtype:'datefield',
										fieldLabel:'毕业时间',
										editable:false,
										name:'clsEtime',
										format:'Y-m-d'
									}
								]
							},
							{
								xtype:'panel',
								columnWidth:.5,
								layout:'form',
								labelAlign:'right',
								labelWidth:80,
								defaults:{width:80},
								labelSeparator:'：',
								items:[
									{
										xtype:'datefield',
										fieldLabel:'到',
										editable:false,
										name:'clsEtime2',
										format:'Y-m-d'
									}
								]
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'combo',
								fieldLabel:'状态',
								mode:'local',
								triggerAction:'all',
								editable:false,
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','全部'],['1','正常'],['2','毕业'],['3','停用']]
								}),
								value:'',
								valueField:'id',
								displayField:'text',
								hiddenName:'clsState'
							}
						]
					}
				]
			}
		],
		buttons:[
			{
				text:'查询',
				handler:function(){
					clsStore.reload({params:{start:0,limit:10}});
				}
			},
			{
				text:'重置',
				handler:function(){
					queryClsForm.getForm().reset();
				}
			}
		]
	});
});