Ext.onReady(function(){
	Ext.QuickTips.init();
	form = new Ext.form.FormPanel({
		renderTo:'mainForm',
		width:550,
		border:false,
		fileUpload:true,
		labelAlign:'right',
		labelSeparator:'：',
		labelWidth:200,
		buttonAlign:'center',
		defaults:{width:240},
		items:[
			{
				xtype:'textfield',
				name:'studName',
				allowBlank:false,
				fieldLabel:'姓名<font color="red">*</font>'
			},
			{
				xtype:'textfield',
				name:'studPwd',
				allowBlank:false,
				inputType:'password',
				fieldLabel:'密码<font color="red">*</font>'
			},
			{
				xtype:'textfield',
				name:'repwd',
				inputType:'password',
				fieldLabel:'再次输入密码<font color="red">*</font>'
			},
			{
				xtype:'numberfield',
				name:'studSid',
				allowBlank:false,
				fieldLabel:'身份证号<font color="red">*(准确输入登录使用)</font>'
			},
			{
				xtype:'textfield',
				name:'studNo',
				fieldLabel:'学号'
			},
			{
				xtype:'radiogroup',
				id:'studSex',
				fieldLabel:'性别<font color="red">*</font>',
				items:[
					{
						xtype:'radio',
						boxLabel:'男',
						name:'studSex',
						inputValue:'1',
						checked:true
					},
					{
						xtype:'radio',
						boxLabel:'女',
						name:'studSex',
						inputValue:'0'
					}
				]
			},
			{
				xtype:'datefield',
				fieldLabel:'出生日期',
				name:'studBirth',
				allowBlank:false,
				editable:false,
				format:'Y-m-d'
			},
			{
				xtype:'panel',
				layout:'hbox',
				width:200,
				border:false,
				fieldLabel:'班级<font color="red">*</font>',
				items:[
					{
						xtype:'textfield',
						name:'studCls',
						hidden:true
					},
					{
						xtype:'textfield',
						name:'studClsName',
						allowBlank:false,
						readOnly:true,
						width:180
					},
					{
						xtype:'button',
						text:'...',
						handler:function(){
							clsWin.show();
						}
					}
				]
			},
			{
				xtype:'numberfield',
				fieldLabel:'电话',
				name:'studTel'
			},
			{
				xtype:'textfield',
				fieldLabel:'地址',
				name:'studAddr'
			},
			{
				xtype:'numberfield',
				fieldLabel:'QQ号',
				name:'studQq'
			},
			{
				xtype:'textfield',
				fieldLabel:'邮箱',
				name:'studEmail',
				vtype:'email',
				validateOnBlur:true
			},
			{
				xtype:'textfield',
				fieldLabel:'密码提示问题<font color="red">*</font>',
				name:'studQues',
				allowBlank:false
			},
			{
				xtype:'textfield',
				fieldLabel:'密码提示答案<font color="red">*</font>',
				name:'studAnswer',
				allowBlank:false
			},
			{
				xtype:'fileuploadfield',
				fieldLabel:'相片',
				name:'file',
				buttonText:'选择..'
			},
			{
				xtype:'textarea',
				fieldLabel:'说明',
				name:'studDesc',
				height:60
			}
		],
		buttons:[
			{
				text:'注册',
				handler:function(){
					var boo = form.getForm().isValid();
					if(!boo){
						return;
					}
					var p1 = form.getForm().findField('studPwd').getValue();
					var p2 = form.getForm().findField('repwd').getValue();
					if(p1!=p2){
						Ext.Msg.alert('提示','两次密码输入不一致！');
						form.getForm().findField('repwd').focus(true);
						return;
					}
					form.getForm().doAction('submit',{
						url:path+'studreg!save.action',
						method:'post',
						waitTitle:'正在保存',
						waitMsg:'正在保存请稍候...',
						success:function(f,opt){
							if(opt.result.success==true){
								if(opt.result.img==false){
									Ext.Msg.alert('提示','不支持的文件类型。');	
								}else{
									if(opt.result.count>0){
										Ext.Msg.alert('提示','身份证号已经存在，请检查你的身份证号是否输入正确！',function(){
											form.getForm().findField('studSid').focus(true);
										});
									}else{
										Ext.Msg.alert('提示','注册成功。<br/>请牢记你的密码。<br/>现在可以登录了。',function(){
											window.location.href=path+"login.action";		
										});										
									}
								}
							}else{
								Ext.Msg.alert('提示','保存不成功。');
							}
						},
						failure:function(f,opt){
							Ext.Msg.alert('服务提示','保存不成功。');
						}
					});
				}
			},
			{
				text:'重写',
				handler:function(){
					form.getForm().reset();
				}
			}
		]
	});	
});