Ext.onReady(function(){
	queryStudForm = new Ext.form.FormPanel({
		frame:true,
		items:[
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'学号',
								name:'studNo'
							}
						]
					},
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'姓名',
								name:'studName'
							}
						]
					},
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'身份证',
								name:'studSid'
							}
						]
					},
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'combo',
								fieldLabel:'性别',
								name:'studSex',
								mode:'local',
								editable:false,
								triggerAction:'all',
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','不限'],['1','男'],['0','女']]
								}),
								valueField:'id',
								displayField:'text',
								hiddenName:'studSex'
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'班级',
								name:'studCls'
							}
						]
					},
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'专业',
								name:'studMajor'
							}
						]
					},
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'学制',
								name:'studEdusys'
							}
						]
					},
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.2,
						labelAlign:'right',
						labelWidth:80,
						defaults:{width:80},
						labelSeparator:'：',
						items:[
							{
								xtype:'textfield',
								fieldLabel:'电话',
								name:'studTel'
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						labelSeparator:'：',
						defaults:{width:80},
						items:[
							{
								xtype:'datefield',
								fieldLabel:'出生日期',
								name:'studBirth',
								format:'Y-d-m',
								editable:false
							}
						]
					},
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						labelSeparator:'：',
						defaults:{width:80},
						items:[
							{
								xtype:'datefield',
								fieldLabel:'到',
								name:'studBirth2',
								format:'Y-d-m',
								editable:false
							}
						]
					},
					{
						xtype:'panel',
						columnWidth:.2,
						layout:'form',
						labelAlign:'right',
						labelWidth:80,
						labelSeparator:'：',
						defaults:{width:80},
						items:[
							{
								xtype:'combo',
								fieldLabel:'状态',
								mode:'local',
								triggerAction:'all',
								editable:false,
								name:'studState',
								store:new Ext.data.ArrayStore({
									idIndex:0,
									fields:['id','text'],
									data:[['','全部'],['1','正常'],['2','流失'],['3','退学'],['4','病假']]
								}),
								valueField:'id',
								displayField:'text',
								hiddenName:'studState'
							}
						]
					}
				]
			},
			{
				xtype:'panel',
				layout:'column',
				items:[
					{
						xtype:'panel',
						layout:'form',
						columnWidth:.4,
						labelAlign:'right',
						labelWidth:80,
						labelSeparator:'：',
						defaults:{width:240},
						items:[
							{
								xtype:'textfield',
								fieldLabel:'地址',
								name:'studAddr'
							}
						]
					}
				]
			}
		],
		buttons:[
			{
				text:'查询',
				handler:function(){
					studStore.reload({params:{start:0,limit:10}});
				}
			},
			{
				text:'重置',
				handler:function(){
					queryStudForm.getForm().reset();
				}
			}
		]
	});
	
})	;